# Generated by Django 5.2.8 on 2025-11-08 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Insumo')),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Producto')),
                ('stock_actual', models.IntegerField(default=0, editable=False, verbose_name='Stock Total')),
                ('umbral_critico', models.IntegerField(default=0, verbose_name='Umbral de Stock Crítico')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Medicina Hombres, Urgencias, Cesfam', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100, verbose_name='Número de Lote')),
                ('fecha_caducidad', models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad')),
                ('fecha_recepcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('stock_por_lote', models.IntegerField(default=0, verbose_name='Stock del Lote')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventory.insumo')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'unique_together': {('insumo', 'numero_lote')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
                ('servicio_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.servicio', verbose_name='Servicio Destino')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_movimiento', to='inventory.lote')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.movimiento')),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento',
                'verbose_name_plural': 'Detalles de Movimientos',
            },
        ),
    ]
